---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: traefik

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-claim
  namespace: traefik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      name: traefik
  template:
    metadata:
      labels:
        k8s-app: traefik
        name: traefik
    spec:
      volumes:
      - name: traefik-volume
        persistentVolumeClaim:
          claimName: traefik-claim
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.0
        name: traefik
        volumeMounts:
        - mountPath: /etc/traefik
          name: traefik-volume
        ports:
        - name: traefik
          containerPort: 8080
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --global.sendAnonymousUsage=false
        - --accesslog=true
        - --log=true
        - --log.level=INFO
        - --api.dashboard=true
        - --api.insecure=true
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --providers.kubernetesIngress
        - --providers.kubernetesCRD
        - --certificatesresolvers.default.acme.email=hostmaster@rask.dk
        - --certificatesresolvers.default.acme.storage=/etc/traefik/acme.json
        - --certificatesresolvers.default.acme.tlschallenge=true
        # Debugging only:
        - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik
  loadBalancerIP: 192.168.0.10
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  - name: traefik
    protocol: TCP
    port: 8080
  # externalIPs:
  # - 192.168.0.4
