---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-v1
  namespace: traefik

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: traefik-v1-claim
#   namespace: traefik
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-v1
  namespace: traefik
spec:
  selector:
    matchLabels:
      name: traefik-v1
  template:
    metadata:
      labels:
        k8s-app: traefik-v1
        name: traefik-v1
    spec:
      # volumes:
      # - name: traefik-v1-volume
      #   persistentVolumeClaim:
      #     claimName: traefik-v1-claim
      serviceAccountName: traefik-v1
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7
        # imagePullPolicy: Always
        name: traefik
        # volumeMounts:
        # - mountPath: /etc/traefik
        #   name: traefik-v1-volume
        ports:
        - name: traefik
          containerPort: 8080
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-v1
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-v1
  loadBalancerIP: 192.168.0.13
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  - name: traefik
    protocol: TCP
    port: 8080
