---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-int-crb

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-v2-cr
subjects:
  - kind: ServiceAccount
    name: traefik-int-sa
    namespace: traefik