---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik2
  namespace: traefik

---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: traefik2
#   namespace: traefik
# data:
#   traefik.toml: |
#     [api]
#     dashboard = true
#     insecure = true

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik2
  namespace: traefik
spec:
  selector:
    matchLabels:
      name: traefik2
  template:
    metadata:
      labels:
        k8s-app: traefik2
        name: traefik2
    spec:
      serviceAccountName: traefik2
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.0
        name: traefik2
        ports:
        - name: http
          containerPort: 80
        - name: traefik
          containerPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api.insecure=true
        - --providers.kubernetesIngress

---
kind: Service
apiVersion: v1
metadata:
  name: traefik2
  namespace: traefik
spec:
  # type: NodePort
  selector:
    k8s-app: traefik2
  ports:
    - protocol: TCP
      port: 80
      # nodePort: 30000
      name: http
    - protocol: TCP
      port: 8080
      # nodePort: 30001
      name: traefik
  externalIPs:
  - 192.168.0.4